# Generated by Django 3.0.7 on 2020-06-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='authhor',
            new_name='author',
        ),
    ]
