# Generated by Django 3.0.7 on 2020-06-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomanyApp', '0003_dojo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dojo',
        ),
    ]
