# Generated by Django 2.2.4 on 2020-04-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theWallApp', '0002_auto_20200423_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
