# Generated by Django 3.0.7 on 2020-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvShowsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='release_date',
            new_name='release',
        ),
    ]
