# Generated by Django 3.0.7 on 2020-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetomanyApp', '0002_author_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='onetomanyApp.Author'),
        ),
    ]
