# Generated by Django 3.0.7 on 2020-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosandninjasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
