# Generated by Django 3.0.7 on 2020-06-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theWallApp', '0004_auto_20200424_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
