# Generated by Django 3.0.7 on 2020-06-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='likes',
        ),
    ]
