# Generated by Django 3.0.7 on 2020-06-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthorsApp', '0002_remove_author_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
