# Generated by Django 3.0.7 on 2020-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksandauthorsApp', '0003_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authors',
            field=models.ManyToManyField(related_name='author_books', to='booksandauthorsApp.Book'),
        ),
    ]
